apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: realworld-secrets
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: realworld-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: realworld-app
        property: jwt-secret
    - secretKey: db-url
      remoteRef:
        key: realworld-app
        property: db-url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: realworld-secrets
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: realworld-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: realworld-app
        property: jwt-secret
    - secretKey: db-url
      remoteRef:
        key: realworld-app
        property: db-url
