apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realworld-production
  namespace: argocd
  labels:
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/iamay0bami/hardened-gitops
    targetRevision: main
    path: gitops/helm/realworld-app
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    # NO automated block = MANUAL SYNC ONLY
    # A human must click Sync in ArgoCD UI or run argocd app sync
    # This protects production from accidental automated deployments
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
